apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: dev-1
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/data'
