apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: dev-1
  labels:
    app: postgres
data:
  POSTGRES_DB: thingsboarddb
  POSTGRES_USER: thingsboard
  POSTGRES_PASSWORD: thingsboard
  SPRING_DATASOURCE_URL: jdbc:postgresql://tb-database:5432/thingsboarddb
  SPRING_DATASOURCE_USERNAME: thingsboard
  SPRING_DATASOURCE_PASSWORD: thingsboard
