apiVersion: v1
kind: Pod
metadata:
  name: thingsboard
  labels:
    env: test
    tier: application
spec:
  containers:
    - name: thingsboard-tb
      image: thingsboard/tb
      imagePullPolicy: IfNotPresent
