apiVersion: apps/v1
kind: Deployment
metadata:
  name: thingsboard-Deployment
  namespace: dev-1
spec:
  selector:
    matchLabels:
      app: thingsboard
  replicas: 3
  template:
    metadata:
      labels:
        app: thingsboard
    spec:
      containers:
        - name: thingsboard-tb
          image: thingsboard/tb
  nodeSelector:
    disktype: ssd
