apiVersion: v1
kind: Service
metadata:
  name: thingsboard-service
  namespace: dev-1
spec:
  selector:
    app: thingsboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: NodePort
